modLoader="javafml"
loaderVersion="[43,)"
license="GNU General Public License v3.0"

[[mods]]
    modId="stabxmodernguns"
    version="3.2"
    displayName="Stabx Modern Guns"
    authors="Stabilizer King"
    credits="Me and All the guys who worked in Stabilizer Gaming Studio"
    description="Addon for Mr.Crayfish's gun mod that adds High Quality Guns With Amazing Sounds"

[[dependencies.stabxmodernguns]]
    modId="forge"
    mandatory=true
    versionRange="[43.2.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.stabxmodernguns]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.19.3)"
    ordering="NONE"
    side="BOTH"
[[dependencies.stabxmodernguns]]
    modId="cgm"
    mandatory=true
    versionRange="[1.3.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.stabxmodernguns]]
    modId="framework"
    mandatory=true
    versionRange="[0.4.2,)"
    ordering="NONE"
    side="BOTH"

[modproperties.stabxmodernguns]
    catalogueItemIcon="stabxmodernguns:m4"
